import AgentGateway
import Foundation
#if canImport(FoundationNetworking)
import FoundationNetworking
#endif

/// How the `models` query resolves pricing. Pricing is looked up only by the
/// dedicated models query; execution paths never load it, and a pricing
/// failure never fails the query — models are simply returned without prices.
public enum GatewayModelPricingMode: String, Sendable {
  /// Fresh cache, then remote fetch, then stale cache, then built-in snapshot.
  case auto
  /// No network: cache, then built-in snapshot.
  case offline
  /// Skip pricing entirely.
  case off
}

/// Attaches best-effort pricing to a model catalog result. Models without a
/// pricing entry keep `pricing == nil`; when no pricing data can be resolved
/// at all, the catalog is returned unchanged.
public func attachGatewayModelPricing(
  to result: GatewayModelCatalogResult,
  mode: GatewayModelPricingMode = .auto
) async -> GatewayModelCatalogResult {
  await attachGatewayModelPricing(to: result, mode: mode, loader: GatewayModelPricingLoader())
}

func attachGatewayModelPricing(
  to result: GatewayModelCatalogResult,
  mode: GatewayModelPricingMode,
  loader: GatewayModelPricingLoader
) async -> GatewayModelCatalogResult {
  guard mode != .off, let store = await loader.load(mode: mode) else { return result }
  var priced = result
  priced.pricingSource = store.source
  priced.models = result.models.map { model in
    var model = model
    model.pricing = store.pricing(for: model.modelId, vendor: result.vendor)
    return model
  }
  return priced
}

/// Pricing keyed by LiteLLM model name. LiteLLM keys Anthropic and OpenAI
/// models bare ("claude-sonnet-4-5", "gpt-5") and prefixes other providers
/// ("gemini/gemini-2.5-pro", "openrouter/anthropic/claude-sonnet-4.5").
struct GatewayModelPricingStore: Sendable {
  var prices: [String: GatewayModelPricing]
  var source: GatewayModelPricingSource

  func pricing(for modelId: String, vendor: GatewayVendor) -> GatewayModelPricing? {
    for key in Self.lookupKeys(for: modelId, vendor: vendor) {
      if let price = prices[key] { return price }
    }
    return nil
  }

  /// CLI vendors price as the API vendor whose models they run
  /// (claude-code -> anthropic, codex -> openai). Cursor has no public
  /// pricing in the LiteLLM database.
  static func lookupKeys(for modelId: String, vendor: GatewayVendor) -> [String] {
    switch vendor {
    case .anthropic, .claudeCode: [modelId, "anthropic/\(modelId)"]
    case .openAI, .codex: [modelId, "openai/\(modelId)"]
    case .gemini: ["gemini/\(modelId)", modelId]
    case .openRouter: ["openrouter/\(modelId)", modelId]
    case .cursor, .cursorAPI: []
    }
  }
}

/// Resolves pricing the way ccusage does, from two layered sources:
///
/// 1. The LiteLLM pricing database (`model_prices_and_context_window.json`).
/// 2. When LiteLLM is unavailable, the fallback pricing table published in
///    the agent-gateway GitHub repository (`data/model-prices.json`, a
///    LiteLLM-format extract regenerated by
///    `scripts/update-model-prices.sh`).
///
/// Each source keeps its own on-disk cache so a run makes at most one
/// pricing request and repeat runs within the cache lifetime make none.
/// Every step is best-effort; `load` returns nil instead of throwing so
/// callers degrade to a price-less catalog.
struct GatewayModelPricingLoader: Sendable {
  struct Source: Sendable {
    var remoteURL: URL
    var cacheFileURL: URL
    var remoteProvenance: GatewayModelPricingSource
    var cacheProvenance: GatewayModelPricingSource
  }

  static let liteLLMRemoteURL = URL(
    string: "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json"
  )!
  static let fallbackTableRemoteURL = URL(
    string: "https://raw.githubusercontent.com/tacogips/agent-gateway/main/data/model-prices.json"
  )!
  static let cacheTimeToLive: TimeInterval = 24 * 60 * 60

  var fetch: @Sendable (URL) async throws -> Data
  var sources: [Source]
  var now: @Sendable () -> Date

  init(
    fetch: @escaping @Sendable (URL) async throws -> Data = Self.fetchOverHTTP,
    cacheDirectoryURL: URL = Self.defaultCacheDirectoryURL(),
    now: @escaping @Sendable () -> Date = Date.init
  ) {
    self.fetch = fetch
    self.sources = [
      Source(
        remoteURL: Self.liteLLMRemoteURL,
        cacheFileURL: cacheDirectoryURL.appendingPathComponent(
          "litellm-model-prices.json", isDirectory: false
        ),
        remoteProvenance: .liteLLMRemote,
        cacheProvenance: .liteLLMCache
      ),
      Source(
        remoteURL: Self.fallbackTableRemoteURL,
        cacheFileURL: cacheDirectoryURL.appendingPathComponent(
          "fallback-model-prices.json", isDirectory: false
        ),
        remoteProvenance: .fallbackTableRemote,
        cacheProvenance: .fallbackTableCache
      )
    ]
    self.now = now
  }

  static func defaultCacheDirectoryURL() -> URL {
    let base = FileManager.default.urls(for: .cachesDirectory, in: .userDomainMask).first
      ?? FileManager.default.temporaryDirectory
    return base.appendingPathComponent("agent-gateway", isDirectory: true)
  }

  @Sendable static func fetchOverHTTP(_ url: URL) async throws -> Data {
    var request = URLRequest(url: url)
    request.httpMethod = "GET"
    request.timeoutInterval = 15
    let (data, response) = try await URLSession.shared.data(for: request)
    guard let http = response as? HTTPURLResponse, (200...299).contains(http.statusCode) else {
      throw GatewayRPCError(code: -32010, message: "pricing database fetch failed")
    }
    return data
  }

  func load(mode: GatewayModelPricingMode) async -> GatewayModelPricingStore? {
    switch mode {
    case .off:
      return nil
    case .offline:
      for source in sources {
        if let cached = cachedStore(source, maxAge: nil) { return cached }
      }
      return nil
    case .auto:
      for source in sources {
        if let fresh = cachedStore(source, maxAge: Self.cacheTimeToLive) { return fresh }
        if let remote = await remoteStore(source) { return remote }
        if let stale = cachedStore(source, maxAge: nil) { return stale }
      }
      return nil
    }
  }

  private func remoteStore(_ source: Source) async -> GatewayModelPricingStore? {
    guard let data = try? await fetch(source.remoteURL) else { return nil }
    let prices = parseLiteLLMModelPrices(data)
    guard !prices.isEmpty else { return nil }
    try? FileManager.default.createDirectory(
      at: source.cacheFileURL.deletingLastPathComponent(), withIntermediateDirectories: true
    )
    try? data.write(to: source.cacheFileURL, options: [.atomic])
    return GatewayModelPricingStore(prices: prices, source: source.remoteProvenance)
  }

  private func cachedStore(_ source: Source, maxAge: TimeInterval?) -> GatewayModelPricingStore? {
    guard let attributes = try? FileManager.default.attributesOfItem(atPath: source.cacheFileURL.path) else {
      return nil
    }
    if let maxAge {
      guard let modified = attributes[.modificationDate] as? Date,
        now().timeIntervalSince(modified) <= maxAge else { return nil }
    }
    guard let data = try? Data(contentsOf: source.cacheFileURL) else { return nil }
    let prices = parseLiteLLMModelPrices(data)
    guard !prices.isEmpty else { return nil }
    return GatewayModelPricingStore(prices: prices, source: source.cacheProvenance)
  }
}

/// Parses LiteLLM's `model_prices_and_context_window.json` shape. Entries
/// without a numeric input or output cost (such as the "sample_spec"
/// documentation entry) are skipped.
func parseLiteLLMModelPrices(_ data: Data) -> [String: GatewayModelPricing] {
  guard let object = (try? JSONSerialization.jsonObject(with: data)) as? [String: Any] else {
    return [:]
  }
  var prices: [String: GatewayModelPricing] = [:]
  prices.reserveCapacity(object.count)
  for (model, value) in object {
    guard let entry = value as? [String: Any] else { continue }
    func cost(_ key: String) -> Double? {
      // NSNumber(0)/NSNumber(1) bridge to Bool, so `is Bool` would drop
      // legitimate zero-cost entries; compare the CF type instead.
      guard let number = entry[key] as? NSNumber,
        CFGetTypeID(number) != CFBooleanGetTypeID() else { return nil }
      return number.doubleValue
    }
    let pricing = GatewayModelPricing(
      inputCostPerToken: cost("input_cost_per_token"),
      outputCostPerToken: cost("output_cost_per_token"),
      cacheReadInputTokenCost: cost("cache_read_input_token_cost"),
      cacheCreationInputTokenCost: cost("cache_creation_input_token_cost")
    )
    guard pricing.inputCostPerToken != nil || pricing.outputCostPerToken != nil else { continue }
    prices[model] = pricing
  }
  return prices
}
